from libqtile.config import Group, Match

workspaces = [
    Group(
        "1",
        label="",
        layout="monadtall",
    ),
    Group(
        "2",
        label="",
        layout="monadtall",
    ),
    Group(
        "3",
        label="",
        layout="monadtall",
    ),
    Group(
        "4",
        label="",
        layout="monadtall",
    ),
    Group(
        "5",
        label="",
        layout="monadtall",
    ),
    Group(
        "6",
        label="",
        layout="monadtall",
    ),
    Group(
        "7",
        label="",
        layout="monadtall",
        matches=[
            Match(wm_class="qemu-system-x86_64"),
        ],
    ),
    Group(
        "8",
        label="",
        layout="monadtall",
    ),
    Group(
        "9",
        label="",
        layout="monadtall",
    ),
    Group(
        "0",
        label="",
        layout="monadtall",
        matches=[
            Match(wm_class="librewolf"),
        ],
    ),
]
