#!/usr/bin/env sh

userresources=$HOME/.config/X11/xresources
usermodmap=$HOME/.config/X11/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

#
# start more nice programs
#

# set default wallpaper
[ -f ~/.local/share/wallpapers/default.jpg ] && hsetroot -cover \
  ~/.local/share/wallpapers/default.jpg &

# fix mouse pointer
xsetroot -cursor_name left_ptr &

# music player daemon
pgrep -x mpd >/dev/null || mpd &

# compositor for transparency
pgrep -x picom >/dev/null || picom --experimental-backends --daemon &

# redshift to adjust display color temperature
pgrep -x redshift >/dev/null || redshift &

# notification daemon to receive desktop notifications and warnings
pgrep -x dunst >/dev/null || dunst &

# launch emacs daemon so emacs opens faster
pgrep -x emacs >/dev/null || emacs --daemon &

# torrent daemon set to start but not automatically restart paused torrents
pgrep -af transmission-daemon >/dev/null || transmission-daemon --paused &

# start polkit agents for apps that need elevated priviliges
pgrep -af polkit-gnome >/dev/null || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# launch window manager
exec bspwm
