#!/usr/bin/env sh

userresources=$HOME/.config/X11/xresources
usermodmap=$HOME/.config/X11/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# programs I set to run when starting X
pgrep -x mpd >/dev/null || mpd &
pgrep -x picom >/dev/null || picom --experimental-backends &
pgrep -x redshift >/dev/null || redshift &
pgrep -x dunst >/dev/null || dunst &
pgrep -x emacs >/dev/null || emacs --daemon &
pgrep -af transmission-daemon >/dev/null || transmission-daemon --paused &
pgrep -af polkit-gnome >/dev/null || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

xsetroot -cursor_name left_ptr &
~/.fehbg &

exec bspwm
