#!/usr/bin/env sh

#
# start yet more nice programs as bspwm is launched
#

# start simple X hotkey daemon that controls my custom keybindings
pgrep -x sxhkd >/dev/null || sxhkd &

# launch statusbar
pgrep -x polybar >/dev/null || "$HOME"/.config/polybar/launch

#
# configuring bspwm via `bspc`
#

# set workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# configure windows
bspc config border_width 3
bspc config window_gap 8

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

# set colors for window borders
bspc config normal_border_color "#727169"
bspc config active_border_color "#1f1f28"
bspc config focused_border_color "#7e9cd8"
bspc config presel_feedback_color "#dcd7ba"

# WM_CLASS rules for apps
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^10' follow=on
bspc rule -a Emacs state=tiled follow=on
bspc rule -a Zathura state=tiled
bspc rule -a mpv state=fullscreen
bspc rule -a qemu-system-x86_64 desktop='^7' state=tiled follow=on

# rules for custom WM_CLASSes
bspc rule -a scratchpad state=floating
bspc rule -a ncmpcpp state=floating
bspc rule -a btm state=floating
bspc rule -a htop state=floating
bspc rule -a qalc state=floating
