#!/usr/bin/env sh

pgrep -x sxhkd >/dev/null || sxhkd &
pgrep -x polybar >/dev/null || $HOME/.config/polybar/launch

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 2
bspc config window_gap 8

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a LibreWolf desktop='^10' follow=on
bspc rule -a Emacs desktop='^9' state=tiled follow=on
bspc rule -a Zathura state=tiled
bspc rule -a qemu-system-x86_64 desktop='^7' state=tiled follow=on

# custom WM_CLASS
bspc rule -a scratchpad state=floating

bspc config normal_border_color "#4c566a"
bspc config active_border_color "#88c0d0"
bspc config focused_border_color "#81a1c1"
bspc config presel_feedback_color "#d8dee9"
